// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKxIaaz-7ssWJHCEbFeLDxiy7yb0q0Rnw',
    appId: '1:657034783615:web:286b04726425bc5b6cc84a',
    messagingSenderId: '657034783615',
    projectId: 'flutternews-c385e',
    authDomain: 'flutternews-c385e.firebaseapp.com',
    storageBucket: 'flutternews-c385e.appspot.com',
    measurementId: 'G-S0KLTMX9H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSqWB1p66WiPNRcIg0GFeiRxNojODjdf4',
    appId: '1:657034783615:android:eb8caa15018be7ef6cc84a',
    messagingSenderId: '657034783615',
    projectId: 'flutternews-c385e',
    storageBucket: 'flutternews-c385e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXhG8msVtkwPMerjKF8D5PDWlL7Z9WFOs',
    appId: '1:657034783615:ios:624e45c507ad479a6cc84a',
    messagingSenderId: '657034783615',
    projectId: 'flutternews-c385e',
    storageBucket: 'flutternews-c385e.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXhG8msVtkwPMerjKF8D5PDWlL7Z9WFOs',
    appId: '1:657034783615:ios:624e45c507ad479a6cc84a',
    messagingSenderId: '657034783615',
    projectId: 'flutternews-c385e',
    storageBucket: 'flutternews-c385e.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKxIaaz-7ssWJHCEbFeLDxiy7yb0q0Rnw',
    appId: '1:657034783615:web:348721fdc7c5907c6cc84a',
    messagingSenderId: '657034783615',
    projectId: 'flutternews-c385e',
    authDomain: 'flutternews-c385e.firebaseapp.com',
    storageBucket: 'flutternews-c385e.appspot.com',
    measurementId: 'G-KSYQZXV9LV',
  );
}
